name: macOS (amd64)

on:
  push:
  workflow_dispatch:
    
jobs:

  ci:
    runs-on: macOS-13
    steps:
      - name: Test
        run: |
          export SIREUM_V=4.20241017.f6e1eff
          mkdir -p ~/Applications ~/Downloads
          curl -JLso ~/Downloads/sireum-ive-mac-amd64.tar.xz https://github.com/sireum/kekinian/releases/download/$SIREUM_V/sireum-ive-mac-amd64.tar.xz
          curl -JLso ~/Downloads/org.sireum.library.m2.zip https://github.com/sireum/kekinian/releases/download/$SIREUM_V/org.sireum.library.m2.zip  
          cd ~/Applications
          tar xf ~/Downloads/sireum-ive-mac-amd64.tar.xz
          cd ~
          tar xf ~/Downloads/org.sireum.library.m2.zip

          export SIREUM_HOME=~/Applications/Sireum
          git clone https://github.com/sireum/logika-examples
          logika-examples/bin/verify.cmd
          "${SIREUM_HOME}/bin/sireum" proyek ive logika-examples