name: Linux 20.04 (amd64)

on:
  push:
  workflow_dispatch:
    
jobs:

  ci:
    runs-on: ubuntu-20.04
    steps:
      - name: Test
        run: |
          export SIREUM_V=4.20241017.f6e1eff
          mkdir -p ~/Applications ~/Downloads
          curl -JLso ~/Downloads/sireum-ive-linux-amd64.tar.xz https://github.com/sireum/kekinian/releases/download/$SIREUM_V/sireum-ive-linux-amd64.tar.xz
          curl -JLso ~/Downloads/org.sireum.library.m2.zip https://github.com/sireum/kekinian/releases/download/$SIREUM_V/org.sireum.library.m2.zip  
          cd ~/Applications
          tar xf ~/Downloads/sireum-ive-linux-amd64.tar.xz 2> /dev/null
          cd ~
          unzip -qq ~/Downloads/org.sireum.library.m2.zip

          export SIREUM_HOME=~/Applications/Sireum

          # z3 4.12+ requires glibc > 2.31 but ubuntu 20.04 and Debian 12 requires
          # glibc v2.31 so replace the z3 entry in versions.properties such that 
          # sireum will  download/install z3 4.11.2
          sed -i '/.*z3.*/c\org.sireum.version.z3=4.11.2' $SIREUM_HOME/versions.properties

          git clone https://github.com/sireum/logika-examples
          logika-examples/bin/verify.cmd
          "${SIREUM_HOME}/bin/sireum" proyek ive logika-examples
